source 'https://rubygems.org'

#gem 'poise-application-git', path: '../application_git'
#gem 'python', path: '../python'
#gem 'rspec'
gem 'berkshelf'
gem 'bundler'
gem 'chef', path: '../../../../chef'
gem 'chefspec'
gem 'dep-selector-libgecode'
gem 'dep_selector'
gem 'foodcritic'
gem 'kitchen-vagrant'
gem 'poise-application', path:  '../../cbsources/application'
gem 'poise-application-python', path: '../../cbsources/application_python'
gem 'poise-application-git', path: '../../cbsources/application_git'
gem 'rake'
gem 'rspec', path: '../../../../rspec'
gem 'rspec-core', path: '../../../../rspec-core'
gem 'rspec-expectations', path: '../../../../rspec-expectations'
gem 'rspec-mocks', path: '../../../../rspec-mocks'
gem 'rspec-support', path: '../../../../rspec-support'
gem 'rubocop'
gem 'test-kitchen'
gem 'vagrant', path: '../../../../vagrant'
gem 'yard'
