source 'https://rubygems.org'

gem 'berkshelf'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'vagrant', path: '../../../../vagrant'
gem 'dep-selector-libgecode'
gem 'dep_selector'
gem 'foodcritic'
gem 'poise-application', path:  '../application'
gem 'poise-application-python', path: '../application_python'
gem 'poise-application-git', path: '../application_git'
gem 'chef', path: '../../../../chef'
gem 'rake'
gem 'rspec'
gem 'bundler'
gem 'rubocop'
gem 'yard'
gem 'chefspec'
