name             'zookeepr'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures zookeepr'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'git'
depends 'application'
#depends 'build-essential'
#depends 'gunicorn'
#depends 'poise'
#depends 'poise-languages'
depends 'poise-python'
depends 'application_python'
#depends 'poise-service'
#depends 'supervisor'
#depends 'python'
